### ISSUE TITLE
Error when saving the page

### ISSUE THREAD

**Issue by Sr-Jon** [nuss/gutenberg-menu-select-block#1]
Hello,

I really liked this block and it's just what I was looking for, but... I have a problem. When I edit the page again, the menu I had selected is not selected, it always shows the same one, that is, it doesn't add the selected attribute to the option.

What can I do to correct it? It would be very helpful.

Thank you.

**Comment by nuss** [comment]
Sorry for this very late reply - I totally missed your comment. I haven't done any work on this in a year or so, so, this repo can be more or regarded as abandoned. However, I am aware of the issue that you mentioned. I've tried to fix it but found myself unable to do so. Sorry for that. Very likely I'm not going to continue to work on this project in the near and not so near future...
